/* DSA Bootcamp assignment tracker
   Data comes from data.js (window.TOPICS), generated by scripts/extract.js */
(() => {
  const TOPICS = window.TOPICS || [];
  const STORE_KEY = 'kk-dsa-progress-v1';
  const DIFFS = ['easy', 'medium', 'hard'];
  const LABEL = { easy: 'Easy', medium: 'Medium', hard: 'Hard', other: 'Practice' };

  const $ = (s, el = document) => el.querySelector(s);
  const viewEl = $('#view');
  const searchEl = $('#global-search');

  const state = { view: 'topic', topic: TOPICS[0]?.id, gdiff: 'easy', diff: 'all', status: 'all', query: '' };
  let progress = load();

  /* ---------- helpers ---------- */
  function load() {
    try { return { done: {}, star: {}, ...JSON.parse(localStorage.getItem(STORE_KEY) || '{}') }; }
    catch { return { done: {}, star: {} }; }
  }
  const save = () => localStorage.setItem(STORE_KEY, JSON.stringify(progress));
  const esc = (s) => String(s ?? '').replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));
  const pct = (a, b) => (b ? Math.round((a / b) * 100) : 0);
  const num = (t) => t.file.slice(0, 2);
  const patternId = (t, p) => `${t.id}-p${p.n}`;
  const topicById = (id) => TOPICS.find((t) => t.id === id);
  const trackIds = (t) => [...t.questions.map((q) => q.id), ...t.patterns.map((p) => patternId(t, p))];
  const solved = (ids) => ids.reduce((n, id) => n + (progress.done[id] ? 1 : 0), 0);
  const allQuestions = TOPICS.flatMap((t) => t.questions.map((q) => ({ ...q, topic: t })));

  const ICON = {
    check: '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M5 12.5l4.5 4.5L19 7.5"/></svg>',
    star: '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 3.5l2.6 5.3 5.9.9-4.3 4.1 1 5.8-5.2-2.7-5.2 2.7 1-5.8-4.3-4.1 5.9-.9z"/></svg>',
    ext: '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M14 4h6v6M20 4l-9 9M18 14v5a1 1 0 0 1-1 1H5a1 1 0 0 1-1-1V7a1 1 0 0 1 1-1h5"/></svg>',
  };

  function toast(msg) {
    const t = $('#toast');
    t.textContent = msg;
    t.classList.add('show');
    clearTimeout(toast.timer);
    toast.timer = setTimeout(() => t.classList.remove('show'), 1800);
  }

  /* ---------- filtering ---------- */
  function passStatus(id) {
    if (state.status === 'todo') return !progress.done[id];
    if (state.status === 'done') return !!progress.done[id];
    if (state.status === 'starred') return !!progress.star[id];
    return true;
  }
  function passQuery(q, topic) {
    if (!state.query) return true;
    const hay = `${q.name} ${q.platform} ${(q.companies || []).join(' ')} ${topic ? topic.title : ''}`.toLowerCase();
    return state.query.toLowerCase().split(/\s+/).every((w) => hay.includes(w));
  }

  /* ---------- components ---------- */
  function checkbox(id, label) {
    return `<label class="check"><input type="checkbox" data-action="done" data-id="${id}" ${progress.done[id] ? 'checked' : ''}>
      <span class="box">${ICON.check}</span><span class="sr-only">Mark “${esc(label)}” as solved</span></label>`;
  }
  function starBtn(id, label) {
    const on = !!progress.star[id];
    return `<button type="button" class="icon-btn star" data-action="star" data-id="${id}" aria-pressed="${on}" aria-label="Star “${esc(label)}”">${ICON.star}</button>`;
  }

  function questionRow(q, i, opts = {}) {
    const title = q.url
      ? `<a class="q-title" href="${esc(q.url)}" target="_blank" rel="noopener">${esc(q.name)}</a>`
      : `<span class="q-title">${esc(q.name)}</span>`;
    const meta = [
      opts.showTopic ? `<a class="tag topic-tag" href="#topic/${q.topic.id}">${esc(q.topic.title)}</a>` : '',
      q.url ? `<span class="plat plat-${q.platform}">${esc(q.platform)}</span>` : '<span class="plat plat-Custom">Write code</span>',
      ...(q.companies || []).map((c) => `<span class="tag company">${esc(c)}</span>`),
    ].join('');
    const code = q.code ? `<details class="code"><summary>Show details</summary><pre tabindex="0"><code>${esc(q.code)}</code></pre></details>` : '';
    return `<li class="q ${progress.done[q.id] ? 'done' : ''}" data-row="${q.id}">
      ${checkbox(q.id, q.name)}
      <span class="q-num">${String(i + 1).padStart(2, '0')}</span>
      <div class="q-main">${title}<div class="q-meta">${meta}</div>${code}</div>
      ${opts.showDiff ? `<span class="diff ${q.difficulty}">${LABEL[q.difficulty]}</span>` : '<span></span>'}
      ${starBtn(q.id, q.name)}
      ${q.url ? `<a class="icon-btn" href="${esc(q.url)}" target="_blank" rel="noopener" aria-label="Open ${esc(q.name)}">${ICON.ext}</a>` : '<span></span>'}
    </li>`;
  }

  function group({ title, cls, items, total, opts, href, delay = 0 }) {
    if (!items.length) return '';
    const ids = total.map((q) => q.id);
    const s = solved(ids);
    const heading = href ? `<a href="${href}">${esc(title)}</a>` : esc(title);
    return `<section class="group ${cls}" data-ids="${ids.join(',')}" style="animation-delay:${delay}ms">
      <header class="group-head">
        <h3><span class="dot"></span>${heading}</h3>
        <span class="g-count">${s}/${ids.length} solved</span>
        <div class="bar" style="--p:${pct(s, ids.length)}"><i></i></div>
      </header>
      <ol class="q-list">${items.map((q, i) => questionRow(q, i, opts)).join('')}</ol>
    </section>`;
  }

  function chip(group, value, label, n, cls = '') {
    const active = state[group] === value;
    return `<button type="button" class="chip ${cls}" data-filter="${group}" data-value="${value}" aria-pressed="${active}">
      ${cls ? '<span class="dot"></span>' : ''}${label}${n != null ? ` <span class="n">${n}</span>` : ''}</button>`;
  }

  function toolbar({ withDiff, counts }) {
    return `<div class="toolbar" role="toolbar" aria-label="Filters">
      ${withDiff ? `<div class="chips">
        ${chip('diff', 'all', 'All', counts.all)}
        ${DIFFS.filter((d) => counts[d]).map((d) => chip('diff', d, LABEL[d], counts[d], d)).join('')}
      </div>` : '<span></span>'}
      <div class="chips">
        ${chip('status', 'all', 'Any status')}
        ${chip('status', 'todo', 'To do')}
        ${chip('status', 'done', 'Solved')}
        ${chip('status', 'starred', '★ Starred')}
      </div>
    </div>`;
  }

  /* ---------- views ---------- */
  function renderNav() {
    $('#topic-nav').innerHTML = TOPICS.map((t) => {
      const ids = trackIds(t);
      const s = solved(ids);
      const current = state.view === 'topic' && !state.query && state.topic === t.id;
      return `<li><a class="topic-link" id="nav-${t.id}" href="#topic/${t.id}" ${current ? 'aria-current="page"' : ''}>
        <span class="tl-num">${num(t)}</span>
        <span class="tl-name">${esc(t.title)}</span>
        <span class="tl-count">${ids.length ? `${s}/${ids.length}` : '—'}</span>
        <span class="tl-bar" style="--p:${pct(s, ids.length)}"><i></i></span>
      </a></li>`;
    }).join('');
    $('#view-topic').toggleAttribute('aria-current', state.view === 'topic');
    $('#view-difficulty').toggleAttribute('aria-current', state.view === 'difficulty');
    if (state.view === 'topic') $('#view-topic').setAttribute('aria-current', 'page');
    if (state.view === 'difficulty') $('#view-difficulty').setAttribute('aria-current', 'page');
    $('#view-topic').href = `#topic/${state.topic}`;
    $('#view-difficulty').href = `#difficulty/${state.gdiff}`;
  }

  function renderHero() {
    const allIds = TOPICS.flatMap(trackIds);
    const s = solved(allIds);
    const byDiff = (d) => allQuestions.filter((q) => q.difficulty === d);
    const stat = (label, list, c) => {
      const ids = list.map((q) => q.id);
      return `<div class="stat" style="--c:${c}"><b>${ids.length}</b><span>${label}</span> <small>${solved(ids)} done</small></div>`;
    };
    const patterns = TOPICS.flatMap((t) => t.patterns.map((p) => ({ id: patternId(t, p) })));
    $('#hero-stats').innerHTML = `
      <div class="ring" style="--p:${pct(s, allIds.length)}" role="img" aria-label="${s} of ${allIds.length} solved">
        <svg viewBox="0 0 40 40"><defs><linearGradient id="ring-grad" x1="0" y1="0" x2="1" y2="1">
          <stop offset="0%" stop-color="hsl(188 92% 56%)"/><stop offset="60%" stop-color="hsl(262 92% 68%)"/><stop offset="100%" stop-color="hsl(320 85% 66%)"/></linearGradient></defs>
          <circle class="track" cx="20" cy="20" r="15.9155"/><circle class="fill" cx="20" cy="20" r="15.9155" pathLength="100"/></svg>
        <div class="ring-label"><b>${pct(s, allIds.length)}%</b><span>${s}/${allIds.length}</span></div>
      </div>
      <div class="stat-grid">
        ${stat('Easy', byDiff('easy'), 'var(--easy)')}
        ${stat('Medium', byDiff('medium'), 'var(--medium)')}
        ${stat('Hard', byDiff('hard'), 'var(--hard)')}
        ${stat('Patterns + Practice', [...patterns, ...byDiff('other')], 'var(--other)')}
      </div>`;
  }

  function renderTopic() {
    const t = topicById(state.topic) || TOPICS[0];
    const ids = trackIds(t);
    const s = solved(ids);
    const counts = { all: t.questions.length };
    DIFFS.forEach((d) => (counts[d] = t.questions.filter((q) => q.difficulty === d).length));

    let html = `<header class="topic-head">
      <div class="topic-index" aria-hidden="true">${num(t)}</div>
      <div>
        <h2>${esc(t.title)}</h2>
        <div class="sub">
          ${DIFFS.filter((d) => counts[d]).map((d) => `<span class="pill ${d}"><span class="dot"></span>${counts[d]} ${LABEL[d]}</span>`).join('')}
          ${t.patterns.length ? `<span class="pill other"><span class="dot"></span>${t.patterns.length} Patterns</span>` : ''}
          ${t.questions.some((q) => q.difficulty === 'other') ? `<span class="pill other"><span class="dot"></span>${t.questions.filter((q) => q.difficulty === 'other').length} Practice</span>` : ''}
          <a class="pill" href="${esc(t.source)}" target="_blank" rel="noopener">View on GitHub ↗</a>
        </div>
      </div>
      ${ids.length ? `<div class="topic-progress"><b>${pct(s, ids.length)}%</b> <span>${s}/${ids.length} solved</span><div class="bar" style="--p:${pct(s, ids.length)}"><i></i></div></div>` : ''}
    </header>`;
    html += t.tips.map((tip) => `<p class="tip"><span aria-hidden="true">💡</span><span>${tip.url ? `<a href="${esc(tip.url)}" target="_blank" rel="noopener">${esc(tip.text)}</a>` : esc(tip.text)}</span></p>`).join('');

    if (!ids.length && !t.images.length && !t.resources.length) {
      viewEl.innerHTML = html + `<div class="empty"><div class="big">🌱</div><h3>No questions here yet</h3><p>The <code>${esc(t.file)}</code> file in the repo is currently empty. Check back after the repo is updated and re-run the extractor.</p></div>`;
      return;
    }

    if (ids.length) html += toolbar({ withDiff: DIFFS.some((d) => counts[d]), counts });

    // difficulty groups
    const visible = t.questions.filter((q) => passStatus(q.id) && passQuery(q));
    let delay = 0;
    DIFFS.forEach((d) => {
      if (state.diff !== 'all' && state.diff !== d) return;
      html += group({ title: LABEL[d], cls: d, items: visible.filter((q) => q.difficulty === d), total: t.questions.filter((q) => q.difficulty === d), delay: (delay += 60) });
    });
    // section groups (e.g. OOP interview questions / practice problems)
    if (state.diff === 'all') {
      const sections = [...new Set(t.questions.filter((q) => q.difficulty === 'other').map((q) => q.section))];
      sections.forEach((sec) => {
        html += group({ title: sec || 'Practice', cls: 'other', items: visible.filter((q) => q.difficulty === 'other' && q.section === sec), total: t.questions.filter((q) => q.section === sec), delay: (delay += 60) });
      });
    }

    // patterns
    if (t.patterns.length) {
      const pv = t.patterns.filter((p) => passStatus(patternId(t, p)));
      const ps = solved(t.patterns.map((p) => patternId(t, p)));
      html += `<section class="group topic" data-ids="${t.patterns.map((p) => patternId(t, p)).join(',')}"><header class="group-head"><h3><span class="dot"></span>Pattern Questions</h3>
        <span class="g-count">${ps}/${t.patterns.length} solved</span><div class="bar" style="--p:${pct(ps, t.patterns.length)}"><i></i></div></header>
        <ol class="pattern-grid">${pv.map((p) => {
          const id = patternId(t, p);
          return `<li class="pattern ${progress.done[id] ? 'done' : ''}" data-row="${id}"><header>
            <b>Pattern ${String(p.n).padStart(2, '0')}</b>${starBtn(id, 'Pattern ' + p.n)}${checkbox(id, 'Pattern ' + p.n)}</header>
            <pre tabindex="0"><code>${esc(p.art)}</code></pre></li>`;
        }).join('')}</ol></section>`;
    }

    // concept resources (OOP)
    if (t.resources.length && state.diff === 'all') {
      html += `<section class="group topic"><header class="group-head"><h3><span class="dot"></span>Important Topics to Read</h3><span class="g-count">${t.resources.length} links</span></header>
        <ul class="res-list">${t.resources.map((r) => `<li><a class="res" href="${esc(r.url)}" target="_blank" rel="noopener"><span class="ic" aria-hidden="true">📘</span>${esc(r.name)}<span class="plat plat-${r.platform}">${esc(r.platform)}</span></a></li>`).join('')}</ul></section>`;
    }

    // images (complexities)
    t.images.forEach((img) => {
      html += `<section class="group topic"><header class="group-head"><h3><span class="dot"></span>${esc(img.title)}</h3></header>
        <div class="gallery">${img.srcs.map((src, i) => `<figure><a href="${esc(src)}" target="_blank" rel="noopener"><img src="${esc(src)}" alt="${esc(img.title)} question sheet ${i + 1}" loading="lazy" width="800" height="600"></a></figure>`).join('')}</div></section>`;
    });

    if (ids.length && !visible.length && !t.patterns.some((p) => passStatus(patternId(t, p)))) {
      html += `<div class="empty"><div class="big">🔍</div><h3>Nothing matches these filters</h3><p>Try switching the status or difficulty filter.</p></div>`;
    }
    viewEl.innerHTML = html;
  }

  function renderDifficulty() {
    const d = state.gdiff;
    const cards = DIFFS.map((x) => {
      const list = allQuestions.filter((q) => q.difficulty === x);
      const s = solved(list.map((q) => q.id));
      return `<a class="diff-card ${x}" id="diff-card-${x}" href="#difficulty/${x}" ${x === d ? 'aria-current="page"' : ''}>
        <h2>${LABEL[x]}</h2><b>${list.length}</b><span>${s} solved · ${TOPICS.filter((t) => t.questions.some((q) => q.difficulty === x)).length} topics</span>
        <div class="bar" style="--p:${pct(s, list.length)}"><i></i></div></a>`;
    }).join('');

    let html = `<div class="diff-hero">${cards}</div>` + toolbar({ withDiff: false });
    let delay = 0;
    TOPICS.forEach((t) => {
      const total = t.questions.filter((q) => q.difficulty === d).map((q) => ({ ...q, topic: t }));
      const items = total.filter((q) => passStatus(q.id));
      html += group({ title: `${num(t)} · ${t.title}`, cls: d, items, total, href: `#topic/${t.id}`, delay: (delay += 40) });
    });
    viewEl.innerHTML = html;
  }

  function renderSearch() {
    const results = allQuestions.filter((q) => passQuery(q, q.topic) && passStatus(q.id) && (state.diff === 'all' || q.difficulty === state.diff));
    const counts = { all: allQuestions.filter((q) => passQuery(q, q.topic)).length };
    DIFFS.forEach((d) => (counts[d] = allQuestions.filter((q) => q.difficulty === d && passQuery(q, q.topic)).length));
    let html = `<header class="topic-head"><div class="topic-index" aria-hidden="true">🔎</div><div><h2>Results for “${esc(state.query)}”</h2>
      <div class="sub"><span class="pill">${results.length} matches across ${new Set(results.map((q) => q.topic.id)).size} topics</span></div></div></header>`;
    html += toolbar({ withDiff: true, counts });
    if (!results.length) {
      html += `<div class="empty"><div class="big">🤔</div><h3>No questions found</h3><p>Try a different keyword like “matrix”, “binary”, “GFG” or “Google”.</p></div>`;
    } else {
      TOPICS.forEach((t, i) => {
        const items = results.filter((q) => q.topic.id === t.id);
        html += group({ title: `${num(t)} · ${t.title}`, cls: 'topic', items, total: items, opts: { showDiff: true }, href: `#topic/${t.id}`, delay: i * 30 });
      });
    }
    viewEl.innerHTML = html;
  }

  function render() {
    renderNav();
    renderHero();
    if (state.query) renderSearch();
    else if (state.view === 'difficulty') renderDifficulty();
    else renderTopic();
  }

  /* ---------- routing ---------- */
  function route() {
    const [view, arg] = location.hash.replace(/^#\/?/, '').split('/');
    if (view === 'difficulty' && DIFFS.includes(arg)) { state.view = 'difficulty'; state.gdiff = arg; }
    else { state.view = 'topic'; state.topic = topicById(arg) ? arg : TOPICS[0].id; }
    state.diff = 'all';
    if (state.query) { state.query = ''; searchEl.value = ''; }
    render();
  }

  /* ---------- events ---------- */
  viewEl.addEventListener('change', (e) => {
    const el = e.target.closest('[data-action="done"]');
    if (!el) return;
    const id = el.dataset.id;
    if (el.checked) progress.done[id] = Date.now(); else delete progress.done[id];
    save();
    document.querySelectorAll(`[data-row="${CSS.escape(id)}"]`).forEach((r) => r.classList.toggle('done', el.checked));
    // refresh counters without re-rendering the list (keeps scroll + focus)
    renderNav(); renderHero(); refreshCounters();
    if (el.checked) toast('Nice! Marked as solved ✅');
  });

  viewEl.addEventListener('click', (e) => {
    const star = e.target.closest('[data-action="star"]');
    if (star) {
      const id = star.dataset.id;
      if (progress.star[id]) delete progress.star[id]; else progress.star[id] = Date.now();
      save();
      star.setAttribute('aria-pressed', !!progress.star[id]);
      return;
    }
    const f = e.target.closest('[data-filter]');
    if (f) { state[f.dataset.filter] = f.dataset.value; render(); }
  });

  // Update group/topic progress bars in place
  function refreshCounters() {
    viewEl.querySelectorAll('.group[data-ids]').forEach((g) => {
      const ids = g.dataset.ids.split(',').filter(Boolean);
      const s = solved(ids);
      const cnt = g.querySelector('.g-count');
      const bar = g.querySelector('.group-head .bar');
      if (cnt) cnt.textContent = `${s}/${ids.length} solved`;
      if (bar) bar.style.setProperty('--p', pct(s, ids.length));
    });
    viewEl.querySelectorAll('.diff-card').forEach((c) => {
      const d = c.id.replace('diff-card-', '');
      const list = allQuestions.filter((q) => q.difficulty === d);
      const s = solved(list.map((q) => q.id));
      c.querySelector('span').textContent = `${s} solved · ${TOPICS.filter((t) => t.questions.some((q) => q.difficulty === d)).length} topics`;
      c.querySelector('.bar').style.setProperty('--p', pct(s, list.length));
    });
    const tp = viewEl.querySelector('.topic-progress');
    if (tp && state.view === 'topic' && !state.query) {
      const ids = trackIds(topicById(state.topic));
      const s = solved(ids);
      tp.innerHTML = `<b>${pct(s, ids.length)}%</b> <span>${s}/${ids.length} solved</span><div class="bar" style="--p:${pct(s, ids.length)}"><i></i></div>`;
    }
  }

  let searchTimer;
  searchEl.addEventListener('input', () => {
    clearTimeout(searchTimer);
    searchTimer = setTimeout(() => { state.query = searchEl.value.trim(); state.diff = 'all'; render(); }, 120);
  });
  document.addEventListener('keydown', (e) => {
    if (e.key === '/' && !/input|textarea/i.test(document.activeElement.tagName)) { e.preventDefault(); searchEl.focus(); }
    if (e.key === 'Escape' && document.activeElement === searchEl && searchEl.value) { searchEl.value = ''; state.query = ''; render(); }
  });

  /* random picker */
  const rDialog = $('#random-dialog');
  function pickRandom() {
    let pool = allQuestions.filter((q) => q.url && !progress.done[q.id]);
    if (state.view === 'topic' && !state.query) {
      const local = pool.filter((q) => q.topic.id === state.topic && (state.diff === 'all' || q.difficulty === state.diff));
      if (local.length) pool = local;
    } else if (state.view === 'difficulty') {
      const local = pool.filter((q) => q.difficulty === state.gdiff);
      if (local.length) pool = local;
    }
    if (!pool.length) { $('#random-body').innerHTML = '<p class="r-name">🎉 You have solved everything!</p>'; $('#random-open').hidden = true; return; }
    const q = pool[Math.floor(Math.random() * pool.length)];
    $('#random-open').hidden = false;
    $('#random-open').href = q.url;
    $('#random-body').innerHTML = `<p class="r-name">${esc(q.name)}</p><div class="q-meta">
      <span class="tag topic-tag">${esc(q.topic.title)}</span><span class="diff ${q.difficulty}">${LABEL[q.difficulty]}</span>
      <span class="plat plat-${q.platform}">${esc(q.platform)}</span>${(q.companies || []).map((c) => `<span class="tag company">${esc(c)}</span>`).join('')}</div>`;
  }
  $('#random-btn').addEventListener('click', () => { pickRandom(); rDialog.showModal(); });
  $('#random-again').addEventListener('click', pickRandom);
  rDialog.addEventListener('click', (e) => { if (e.target === rDialog) rDialog.close(); }); // light-dismiss fallback

  /* reset */
  const resetDialog = $('#reset-dialog');
  $('#reset-btn').addEventListener('click', () => resetDialog.showModal());
  resetDialog.addEventListener('click', (e) => { if (e.target === resetDialog) resetDialog.close(); });
  resetDialog.addEventListener('close', () => {
    if (resetDialog.returnValue === 'confirm') { progress = { done: {}, star: {} }; save(); render(); toast('Progress reset'); }
  });

  window.addEventListener('hashchange', () => { route(); window.scrollTo({ top: 0, behavior: 'smooth' }); });
  if (!location.hash) history.replaceState(null, '', `#topic/${TOPICS[0].id}`);
  route();
})();
